interface CategorySeoDefinition {
  name: string;
  description: string;
  searchTerms: string[];
}

export const categorySeoBySlug: Record<string, CategorySeoDefinition> = {
  'plastic-cups': {
    name: 'Gold Trophy Cups',
    description: 'Customizable gold-finish trophy cups for competitions, schools and ceremonies.',
    searchTerms: ['trophy cup', 'gold cup', 'winner trophy', 'championship cup'],
  },
  'metal-cups': {
    name: 'Metal Trophy Cups',
    description: 'Premium metal trophy cups for championships, tournaments and formal recognition.',
    searchTerms: ['metal trophy cup', 'championship cup', 'winner cup', 'award trophy'],
  },
  'metal-plates-with-box': {
    name: 'Award Plates with Presentation Boxes',
    description: 'Decorative award plates supplied with formal presentation boxes for recognition.',
    searchTerms: ['award plate', 'presentation plate', 'award with box', 'honour plate'],
  },
  'plastic-fitted': {
    name: 'Achievement Trophies',
    description: 'Ready-to-customize achievement trophies in sports and recognition designs.',
    searchTerms: ['achievement trophy', 'sports trophy', 'winner award', 'school trophy'],
  },
  'wooden-models': {
    name: 'Mementos & Recognition Awards',
    description:
      'Distinctive mementos and recognition awards in plaque, shield and designer forms.',
    searchTerms: ['memento award', 'recognition award', 'wooden memento', 'custom award'],
  },
  'acrylic-models': {
    name: 'Acrylic Mementos & Awards',
    description:
      'Contemporary acrylic mementos and awards for corporate and institutional recognition.',
    searchTerms: ['acrylic award', 'acrylic memento', 'corporate award', 'custom memento'],
  },
  'corporate-awards': {
    name: 'Corporate Recognition Awards',
    description:
      'Professional corporate awards for achievement, leadership and employee recognition.',
    searchTerms: ['corporate award', 'employee recognition award', 'business trophy', 'star award'],
  },
  'wooden-awards': {
    name: 'Wooden Plaques & Awards',
    description: 'Wood-finish plaques and presentation awards for appreciation and achievement.',
    searchTerms: ['wooden award', 'wooden plaque', 'appreciation award', 'recognition plaque'],
  },
  'la-aca-ra-f-models': {
    name: 'Designer Awards & Frames',
    description: 'Designer acrylic, wood-finish and resin awards with premium presentation frames.',
    searchTerms: ['designer award', 'resin award', 'award frame', 'acrylic award'],
  },
  'fibre-cups': {
    name: 'Fibre Trophy Cups',
    description: 'Lightweight fibre trophy cups for tournaments, schools and award ceremonies.',
    searchTerms: ['fibre trophy cup', 'winner cup', 'school trophy', 'competition award'],
  },
  'ic-models': {
    name: 'Designer Cup Trophies',
    description: 'Tall designer cup trophies with colorful columns and distinctive trophy toppers.',
    searchTerms: ['designer trophy', 'tall trophy cup', 'winner trophy', 'column trophy'],
  },
  'bases-and-accessories': {
    name: 'Trophy Bases, Medals & Accessories',
    description: 'Trophy bases, medals, sports figures, badges and components for award assembly.',
    searchTerms: ['trophy accessories', 'trophy base', 'award medal', 'trophy figure'],
  },
};

interface CuratedGroup {
  skus: string;
  labels: string[];
}

const curatedGroups: CuratedGroup[] = [
  {
    skus: 'PC-117|PC-118|PC-20|PC-21|PC-216|PC-219|PC-22|PC-220|PC-221|PC-222|PC-223|PC-224|PC-225|PC-230|PC-24|PC-241|PC-242|PC-243|PC-244|PC-27|PC-300|PC-301|PC-302|PC-305|PC-309|PC-311|PC-312|PC-313|PC-315|PC-318|PC-32|PC-320|PC-321|PC-322|PC-324|PC-326|PC-327|PC-33|PC-34|PC-346|PC-35|PC-401|PC-402|PC-403|PC-404|PC-405|PC-406|PC-407|PC-408|PC-409|PC-410|PC-411|PC-412|PC-413|PC-414|PC-415|PC-416|PC-417|PC-418|PC-419|PC-421|PC-422|PC-423|PC-424|PC-425|PC-426|PC-50|PC-51|PC-73',
    labels: [
      'Crystal-Top Red Column Victory Cup Trophy',
      'Crystal-Top Red Tower Victory Cup Trophy',
      'Regal Lidded Twin-Handle Gold Cup Trophy',
      'Crescent-Handle Royal Gold Cup Trophy',
      'Crystal-Top Classic Gold Cup Trophy',
      'Wide Petal Gold Celebration Cup Trophy',
      'Fluted Grand Champion Gold Cup Trophy',
      'Winged Star Gold Achievement Trophy',
      'Spiral Wing Gold Cup Trophy',
      'Lattice Shield Gold Cup Trophy',
      'Ornate Leaf Gold Cup Trophy',
      'Twin-Tier Crystal Gold Cup Trophy',
      'Lattice Column Gold Cup Trophy',
      'Scalloped Twin-Handle Gold Cup Trophy',
      'Red Panel Royal Gold Cup Trophy',
      'Blue Column Regal Gold Cup Trophy',
      'Red Column Regal Gold Cup Trophy',
      'Winged Globe Star Achievement Trophy',
      'Turquoise Cone Gold Cup Trophy',
      'Wreath Medallion Gold Trophy',
      'Tall Fluted Gold Cup Trophy',
      'Ribbed Royal Gold Cup Trophy',
      'Classic Scroll-Handle Gold Cup Trophy',
      'Spiral Lidded Gold Cup Trophy',
      'Blue Panel Crown Gold Cup Trophy',
      'Sculpted Wave Gold Trophy',
      'Red V-Panel Gold Trophy',
      'Medallion Crown Gold Cup Trophy',
      'Red Chevron Royal Gold Cup Trophy',
      'Embossed Classic Gold Cup Trophy',
      'Diamond Crest Gold Cup Trophy',
      'Silver Accent Crown Cup Trophy',
      'Red Accent Crown Cup Trophy',
      'Engraved Laurel Gold Cup Trophy',
      'Red Diamond Panel Gold Cup Trophy',
      'Tall Filigree Gold Cup Trophy',
      'Winged Filigree Gold Cup Trophy',
      'Ribboned Classic Gold Cup Trophy',
      'Red Sail Gold Achievement Trophy',
      'Red Crown Filigree Gold Cup Trophy',
      'Classic Scroll-Handle Winner Cup Trophy',
      'Red Lotus Crystal Gold Cup Trophy',
      'Medallion Red Crown Gold Cup Trophy',
      'Red Shield Crown Gold Cup Trophy',
      'Tall Red Column Gold Cup Trophy',
      'Black Accent Royal Gold Cup Trophy',
      'Engraved Tapered Gold Cup Trophy',
      'Crystal Torch Achievement Trophy',
      'Flame First-Place Gold Trophy',
      'Medallion Wing Gold Trophy',
      'Laurel Embossed Gold Cup Trophy',
      'Floral Scroll Gold Cup Trophy',
      'Royal Crown Gold Cup Trophy',
      'Jewel Crown Gold Cup Trophy',
      'Grand Crown Gold Cup Trophy',
      'Red Column Medallion Trophy',
      'Tall Crest Gold Achievement Trophy',
      'Crystal Ring Gold Achievement Trophy',
      'Red Column Lidded Gold Cup Trophy',
      'Turquoise Column Lidded Gold Cup Trophy',
      'Tall Red Fluted Gold Cup Trophy',
      'Tall Turquoise Fluted Gold Cup Trophy',
      'Crystal Orb Red Wing Trophy',
      'Crystal Orb Turquoise Wing Trophy',
      'Flame Crest Gold Trophy',
      'Red Orb Winged Gold Trophy',
      'Medallion Red Orb Winged Trophy',
      'Red Winged Orb Gold Trophy',
      'Crystal-Top Laurel Gold Cup Trophy',
    ],
  },
  {
    skus: 'MC-102|MC-107|MC-108|MC-115|MC-123|MC-124|MC-131|MC-132|MC-134|MC-135|MC-136|MC-137|MC-138|MC-139|MC-140|MC-141|MC-142|MC-143|MC-144|MC-146|MC-147|MC-148|MC-149|MC-150|MC-56|MC-57|MC-58',
    labels: [
      'Crystal-Top Diamond Metal Cup Trophy',
      'Crystal-Top Ribbed Metal Cup Trophy',
      'Wide Crown Metal Championship Cup',
      'Silver Panel Tall Metal Cup Trophy',
      'Silver Accent Tower Metal Cup Trophy',
      'Crystal-Top Lattice Metal Cup Trophy',
      'Tall Pierced Metal Cup Trophy',
      'Blue and Silver Winged Metal Cup Trophy',
      'Blue Column Silver Metal Cup Trophy',
      'Red Crown Tall Metal Cup Trophy',
      'Red Column Wide Metal Cup Trophy',
      'Silver Wing Gold Panel Metal Cup Trophy',
      'Crown Bowl Classic Metal Cup Trophy',
      'Royal Floral Metal Championship Cup',
      'Tall Crown Metal Championship Cup',
      'Tapered Crown Metal Cup Trophy',
      'Pierced Crown Metal Cup Trophy',
      'Embossed Crown Metal Cup Trophy',
      'Lattice Crown Metal Cup Trophy',
      'Royal Ribboned Metal Cup Trophy',
      'Lidded Classic Metal Cup Trophy',
      'Silver Accent Royal Metal Cup Trophy',
      'Tall Lidded Metal Championship Cup',
      'Scroll-Handle Metal Championship Cup',
      'Wide Fluted Metal Victory Cup Trophy',
      'Crystal-Top Leaf Metal Cup Trophy',
      'Diamond Bowl Metal Cup Trophy',
    ],
  },
  {
    skus: 'MP-01|MP-02|MP-03|MP-04|MP-05|MP-06|MP-07|MP-08',
    labels: [
      'Fluted Gold Honour Plate with Green Presentation Box',
      'Beaded Gold Honour Plate with Blue Presentation Box',
      'Spiral Gold Honour Plate with Blue Presentation Box',
      'Silver Centre Honour Plate with Blue Presentation Box',
      'Silver Laurel Honour Plate with Blue Presentation Box',
      'Silver Rope-Border Honour Plate with Blue Presentation Box',
      'Antique Gold Honour Plate with Blue Presentation Box',
      'Ornate Gold Honour Plate with Blue Presentation Box',
    ],
  },
  {
    skus: 'FC-02|FC-06|FC-07|FC-08|FC-09|FC-17|FC-18|FC-23|FC-24|FC-25|FC-26|FC-27|FC-28|FC-29|FC-30|FC-31|FC-33|FC-34',
    labels: [
      'Pink Crown Fibre Cup Trophy',
      'Tall Column Pink Crown Fibre Cup Trophy',
      'Pink Lidded Fibre Cup Trophy',
      'Wide Winged Fibre Victory Cup Trophy',
      'Lattice Wing Fibre Cup Trophy',
      'Red and White Fibre Cup Trophy',
      'Red Crown White Fibre Cup Trophy',
      'Red Pierced Crown Fibre Cup Trophy',
      'Gold Pierced Crown Fibre Cup Trophy',
      'Gold Bowl White Fibre Cup Trophy',
      'Red Column White Fibre Cup Trophy',
      'Black Column Gold Bowl Fibre Cup Trophy',
      'White Pedestal Fibre Cup Trophy',
      'Gold Bowl White Pedestal Fibre Cup Trophy',
      'Red Stem Lattice Fibre Cup Trophy',
      'Star Crest White Fibre Cup Trophy',
      'Flame Crest White Fibre Cup Trophy',
      'Medallion Crest White Fibre Cup Trophy',
    ],
  },
  {
    skus: 'IC-02|IC-03|IC-04|IC-14|IC-15|IC-16|IC-18',
    labels: [
      'Blue Cone Silver Cup Trophy',
      'Purple Flame Gold Cup Trophy',
      'Gold V-Column Cup Trophy',
      'Red Crown Tall Gold Cup Trophy',
      'Flame Crest Purple Column Trophy',
      'Cricket Player Black Column Trophy',
      'Red Crown Classic Cup Trophy',
    ],
  },
  {
    skus: 'AA-9401|AA-9406|AA-9407|AA-9413|AA-9417|AA-9419|AP-9501|AP-9502|AP-9503|AP-9504|AP-9505',
    labels: [
      'Blue Swoosh Acrylic Recognition Award',
      'Blue Oval Acrylic Recognition Award',
      'Shield Column Acrylic Achievement Award',
      'Faceted Round Acrylic Excellence Award',
      'Rainbow Flame Acrylic Recognition Award',
      'Rainbow Wave Acrylic Appreciation Award',
      'Blue Oval Glitter Acrylic Leadership Award',
      'Purple Wave Acrylic Leadership Award',
      'Rainbow Wing Acrylic Achievement Award',
      'Rainbow Flame Tower Acrylic Excellence Award',
      'Orange Flame Acrylic Leadership Award',
    ],
  },
  {
    skus: 'ACA-201|ACA-202|ACA-203|ACA-204|ACA-205|ACA-206|F-01|F-04|F-05|F-06|F-07|LA-101|LA-102|LA-103|LA-104|LA-105|LA-106|LA-107|LA-108|RA-401|RA-402|RA-403|RA-404|RA-405|RA-406|RA-407',
    labels: [
      'Rising Star Acrylic Achievement Award',
      'Red Star Acrylic Honour Award',
      'Twin-Star Wave Acrylic Recognition Award',
      'Geometric Star Acrylic Excellence Award',
      'Victory Fist Acrylic Appreciation Award',
      'Star Torch Acrylic Performance Award',
      'Ornate Gold Plate Presentation Frame',
      'Handshake Corporate Presentation Frame',
      'Medal and Citation Presentation Frame',
      'Emblem and Citation Presentation Frame',
      'Star Medal Corporate Presentation Frame',
      'Leaf Lattice Recognition Memento',
      'Arched Lattice Recognition Memento',
      'Hourglass Lattice Recognition Memento',
      'Rectangular Lattice Appreciation Memento',
      'Circular Leaf Lattice Recognition Memento',
      'Silver Wave Citation Memento',
      'Medallion Pillar Recognition Memento',
      'Hexagon Crest Recognition Memento',
      'Golden Star Swirl Resin Award',
      'Flame Star Golden Resin Award',
      'Golden Dancer Resin Achievement Award',
      'Golden Victory Figure Resin Award',
      'Open Star Golden Resin Award',
      'Golden Handshake Resin Award',
      'Winged Stars Golden Resin Award',
    ],
  },
  {
    skus: 'CA-7009|CA-7010|CA-7012|CA-7013|CA-7014|CA-7015|CA-7016|CA-7018|CA-7019|CA-7020|CA-7021|CA-7023|CA-7024|CA-7025|CA-7026|CA-7028|CA-7029|CA-7030|CA-7031|CA-7032|CA-7033|CA-7034|CA-7035|CA-7337|CA-7383|CA-7389|CA-7396|CA-7511|CA-7562|CA-7583|CA-7587|CA-7611|CA-7690|CA-7903|CA-7904|CA-7906|CA-8002|CA-8004|CA-8006|CA-8102|CA-8104|CA-8201|CA-8204|CA-8301|CA-8302|CA-8303',
    labels: [
      'Triple-Star Red Column Corporate Trophy',
      'Rising Star Corporate Achievement Trophy',
      'Crystal Globe Black Column Corporate Award',
      'Crystal Diamond Red Column Corporate Award',
      'Shooting Star Crystal Column Corporate Award',
      'Triple-Star Crystal Column Corporate Award',
      'Crystal Crown Red Column Corporate Award',
      'Sweeping Star Black Column Corporate Trophy',
      'Twin-Star Ring Corporate Trophy',
      'Crystal Loop Black Column Corporate Award',
      'Star Loop Black Column Corporate Award',
      'Rising Stars Silver Arc Corporate Trophy',
      'Golden Sail Corporate Recognition Trophy',
      'Gold Cup Black Presentation Plaque',
      'Victory Figure Black Presentation Plaque',
      'Triple-Star Red Pillar Corporate Trophy',
      'Gold Star Red Pillar Corporate Trophy',
      'Triple-Star Cup Corporate Trophy',
      'Crystal Crown Black Glitter Corporate Award',
      'Gold Star Red Column Corporate Trophy',
      'Star Cluster Corporate Achievement Trophy',
      'Geometric Star Corporate Achievement Trophy',
      'Round Emblem Corporate Recognition Trophy',
      'Monogram Circle Corporate Recognition Trophy',
      'Triple-Star Crystal Ring Corporate Award',
      'Single-Star Red Column Corporate Award',
      'Silver-Star Green Column Corporate Award',
      'Silver-Star Red Column Corporate Award',
      'Angular Star Crystal Corporate Trophy',
      'Rising Stars Corporate Desk Trophy',
      'Crystal Star Ring Corporate Award',
      'Cascade Stars Corporate Desk Trophy',
      'Shooting Star Swirl Corporate Trophy',
      'Wreath Star Corporate Excellence Trophy',
      'Crystal Globe Blue Column Corporate Award',
      'Twin-Star Silver Column Corporate Award',
      'Gold Shield Corporate Desk Award',
      'Wave Crest Corporate Desk Award',
      'Shadow-Box Star Corporate Award',
      'Magenta Glass Corporate Recognition Award',
      'Tall Purple Glass Corporate Recognition Award',
      'Lattice Frame Corporate Desk Award',
      'Geometric Frame Corporate Desk Award',
      'Crown Heart Corporate Excellence Trophy',
      'Gold Star Pillar Corporate Excellence Trophy',
      'Victory Figure Corporate Excellence Trophy',
    ],
  },
  {
    skus: 'WA-02|WA-06|WA-14|WA-15|WA-16|WA-17|WA-18|WA-20|WA-21|WA-22|WA-23|WA-24|WA-26|WA-28|WA-29|WA-30|WA-31|WA-32|WA-33|WA-34|WA-35|WA-36|WA-37|WA-38|WA-39|WA-40|WA-41|WA-42|WA-44|WA-46|WA-47|WA-48',
    labels: [
      'Arched Black and White Recognition Plaque',
      'Gold Emblem Rosewood Pillar Award',
      'Blue Shield Employee Recognition Award',
      'Blue Arch Safety Recognition Award',
      'Black Lattice Appreciation Plaque',
      'Oval Lattice Leadership Plaque',
      'Diagonal Cup Appreciation Plaque',
      'Silver Lattice Achievement Plaque',
      'Black Pyramid Leadership Award',
      'White Arch Recognition Plaque',
      'Black Arch Dealer Recognition Award',
      'Star Feature Rosewood Presentation Plaque',
      'Gold Lattice Guest Recognition Plaque',
      'Shadow-Box Star Rosewood Award',
      'Black and Gold Music Recognition Plaque',
      'Gold Shield Rosewood Recognition Plaque',
      'Gold Star Rosewood Performance Plaque',
      'Geometric Gold-Stripe Recognition Plaque',
      'Gold Frame Performance Recognition Plaque',
      'Shield Accent Rosewood Appreciation Plaque',
      'Black Art-Deco Recognition Plaque',
      'White Pattern Corporate Recognition Plaque',
      'Wood-Panel White Excellence Plaque',
      'Angled Wood-Panel Recognition Award',
      'Silver and Wood-Panel Recognition Award',
      'White Wood-Panel Festival Recognition Award',
      'Black and Gold President Recognition Award',
      'Gold Panel Black Excellence Award',
      'Angled White Appreciation Award',
      'Slim Black and Gold Appreciation Award',
      'White Diagonal Recognition Award',
      'Hexagon Feature White Recognition Award',
    ],
  },
  {
    skus: 'PF-100|PF-1110|PF-1112|PF-1114|PF-1116|PF-1117|PF-1119|PF-112|PF-1120|PF-1121|PF-1122|PF-1123|PF-1124|PF-1125|PF-1126|PF-1127|PF-1128|PF-1129|PF-1130|PF-1131|PF-116|PF-117|PF-118|PF-1201|PF-1202|PF-1204|PF-1205|PF-1206|PF-1207|PF-1208|PF-1209|PF-1210|PF-1211|PF-1250|PF-128|PF-129|PF-1302|PF-1303|PF-1304|PF-131|PF-132|PF-133|PF-147|PF-148|PF-149|PF-151|PF-152|PF-154|PF-155|PF-156|PF-157|PF-159|PF-160|PF-1601|PF-1602|PF-1604|PF-1605|PF-1606|PF-1607|PF-1608|PF-161|PF-1610|PF-1611|PF-1612|PF-1613|PF-162|PF-163|PF-164|PF-165|PF-166|PF-170|PF-171|PF-172|PF-173|PF-174|PF-175|PF-176|PF-177|PF-178|PF-84|PF-85|PF-86|PF-90|PF-92|PF-93|PF-96|PF-97|PF-98|PF-99',
    labels: [
      'Cricket Star Cluster Gold Trophy',
      'Cricket Player Red Ball Gold Trophy',
      'Winged Medallion Gold Achievement Trophy',
      'Winged Star Medallion Gold Trophy',
      'Seven-Star Ring Black Column Trophy',
      'Victory Figure Globe Gold Trophy',
      'Octagonal Gold Presentation Plate Trophy',
      'Crown Heart Gold Achievement Trophy',
      'Ornate Gold Portrait Frame Award',
      'Oval Gold Portrait Frame Award',
      'Floral Round Gold Presentation Award',
      'Royal Oval Gold Presentation Award',
      'Shield Crest Gold Recognition Trophy',
      'Crown Laurel Gold Achievement Trophy',
      'Crown Victory Figure Gold Trophy',
      'Laurel Medallion Gold Cup Trophy',
      'Crown Crest Gold Achievement Trophy',
      'Laurel Victory Figure Gold Award',
      'Royal Twin-Handle Gold Cup Trophy',
      'Open Book Gold Achievement Trophy',
      'Sunburst Medallion Gold Trophy',
      'Laurel Star Gold Achievement Trophy',
      'Flame Leaf Gold Recognition Trophy',
      'Twin-Star Laurel Gold Trophy',
      'Classic Gold Victory Cup Trophy',
      'Laurel Shield Gold Recognition Trophy',
      'Rising Star Gold Achievement Trophy',
      'Sunburst Crest Gold Achievement Trophy',
      'Winged Laurel Gold Achievement Trophy',
      'Spiral Star Gold Recognition Trophy',
      'Creative Pillars Gold Achievement Trophy',
      'Crown Laurel Medallion Gold Trophy',
      'Sunray Crest Gold Achievement Trophy',
      'Geometric Laurel Gold Achievement Trophy',
      'Star Ring Gold Recognition Trophy',
      'Fountain Pen Gold Achievement Trophy',
      'Winged Laurel Emblem Gold Trophy',
      'Oval Star Gold Achievement Trophy',
      'Moon and Stars Gold Recognition Trophy',
      'Cricket Shield Gold Trophy',
      'Cricket Batter Gold Trophy',
      'Cricket Ball Shield Gold Trophy',
      'Classic Round Gold Presentation Trophy',
      'Laurel Round Gold Achievement Trophy',
      'Winged Flame Gold Recognition Trophy',
      'Badminton Player Gold Trophy',
      'Hands and Medallion Gold Trophy',
      'Cricket Bowler Gold Trophy',
      'Column Crest Gold Achievement Trophy',
      'Star Laurel Gold Recognition Trophy',
      'Star Crest Gold Achievement Trophy',
      'Black Column Medallion Gold Trophy',
      'Classic Gold Presentation Plate Trophy',
      'Compact Gold Victory Cup Trophy',
      'Angular Emblem Gold Recognition Trophy',
      'Laurel Emblem Gold Achievement Trophy',
      'Curved Rising Star Gold Trophy',
      'Star Swirl Gold Achievement Trophy',
      'Winged Oval Gold Recognition Trophy',
      'Diamond-Handle Gold Victory Cup Trophy',
      'Cricket Bowler Crescent Gold Trophy',
      'Victory Medallion Gold Achievement Trophy',
      'Curved Star Gold Recognition Trophy',
      'Crown Heart Gold Corporate Award',
      'Open Star Gold Achievement Trophy',
      'Cricket Player Star-Arch Gold Trophy',
      'Football Shield Gold Trophy',
      'Crown Wings Gold Achievement Trophy',
      'Twin-Racket Badminton Gold Trophy',
      'Cricket Player Shield Gold Trophy',
      'Cricket Laurel Gold Achievement Trophy',
      'Badminton Star Gold Achievement Trophy',
      'Student Star Gold Achievement Trophy',
      'Open Book Student Gold Award',
      'Golden Lion Leadership Trophy',
      'Camera and Film Gold Achievement Trophy',
      'Music and Arts Gold Achievement Trophy',
      'Academic Stars Gold Achievement Trophy',
      'Victory Figure Star Gold Trophy',
      'Football Crown Gold Trophy',
      'Hockey Star Crest Gold Trophy',
      'Football Star Shield Gold Trophy',
      'Athletics Star Gold Achievement Trophy',
      'Victory Star Arch Gold Trophy',
      'Sunburst Wreath Gold Achievement Trophy',
      'Red Floral Round Gold Presentation Award',
      'Cricket Batter Gold Sports Trophy',
      'Microphone Gold Performance Trophy',
      'Racket and Stars Gold Sports Trophy',
    ],
  },
  {
    skus: 'PW-1312|PW-1317|PW-1357|PW-1363|PW-1365|PW-1368|PW-1371|PW-1372|PW-1374|PW-1376|PW-1381|PW-1382|PW-1383|PW-1384|PW-1385|PW-1386|PW-1400|PW-1402|PW-1403|PW-1404|PW-1405|PW-1406|PW-1407|PW-1501|PW-1502|PW-1503|PW-1504|PW-1505|PW-1506|PW-1507|PW-1508|PW-1509|PW-1510|PW-1511|PW-1512|PW-1513|PW-1514|PW-1516|PW-1517|PW-1518|PW-1519|PW-1520|PW-3014|PW-3018|PW-3020|PW-3021|PW-3022|PW-3023|PW-3024|PW-3025|PW-3026|PW-3607|PW-4001|PW-4003|PW-4004|PW-4013|PW-4014|PW-4015|PW-4018|PW-4019|PW-4020|PW-4050|PW-4051|PW-4057|PW-4058|PW-6817|PW-6819|PW-6820|PW-6821|W-1311|W-1315|W-1318|W-1451|W-1452|W-1454|W-1455|W-1456|W-2521|W-2522|W-2523|W-2524|W-2525|W-2526|W-2528|W-2529|W-2530|W-2531|W-2533|W-2534|W-2535|W-2536|W-2537|W-2538|W-2539|W-3483|W-3484|W-3485|W-3487|W-3507|W-3513|W-3517|W-3518|W-3519|W-3520|W-3523|W-3524|W-3525|W-3601|W-3602|W-3603|W-3604|W-3605|W-3606|W-4005|W-4008|W-4009|W-4010|W-4011|W-4012|W-4710|W-4711|W-4712|W-4713|W-4714|W-4715|W-4716|W-4717|W-4718|W-4719|W-4720|W-4721|W-4722|W-4723|W-4724|W-4725|W-4726|W-5004|W-5005|W-5006|W-5007|W-5008|W-5053|W-5054|W-6224|W-6226|W-6227|W-6231|W-6813|W-6814|W-6824|W-6828|W-6829|W-6830|W-6831|W-6832|W-6833|W-6834|W-6851|W-6856|W-6857|W-6858|W-6859|W-6860|W-6861|W-6862|W-6863|W-6864|W-6877|W-6878|W-6880|W-6884|W-6890|W-6891|W-6892',
    labels: [
      'Red Flame Medallion Recognition Memento',
      'Twin-Stripe Star Recognition Memento',
      'Gold Flame White Recognition Memento',
      'Gold Lattice White Honour Memento',
      'Arched Star White Recognition Memento',
      'Twin-Panel Medallion Recognition Memento',
      'Abstract Circle Black and Gold Memento',
      'Gold Leaf Black Recognition Memento',
      'Gold Leaf Shield Recognition Memento',
      'Oval Black and Gold Appreciation Memento',
      'Football Player White Sports Memento',
      'Cricket Player White Sports Memento',
      'Running Athlete White Sports Memento',
      'Volleyball Player White Sports Memento',
      'Basketball Player White Sports Memento',
      'Kabaddi Players White Sports Memento',
      'Star Medallion White Achievement Trophy',
      'Shield Medallion White Achievement Trophy',
      'Geometric Wave White Recognition Trophy',
      'Badminton Shuttle Wood-Finish Trophy',
      'Fork Crest Wood-Finish Achievement Trophy',
      'Round Cutout Wood-Finish Achievement Trophy',
      'Open Crest Wood-Finish Recognition Trophy',
      'Ornate Medallion Wood-Finish Trophy',
      'Layered Red Shield Recognition Trophy',
      'Curved Cricket Wood-Finish Trophy',
      'Star Crest Wood-Finish Recognition Trophy',
      'Cup Crest Wood-Finish Achievement Trophy',
      'Crown Shield Wood-Finish Recognition Trophy',
      'Leaf Shield Wood-Finish Recognition Trophy',
      'Rosette Pillar Wood-Finish Sports Trophy',
      'Classic Arch Wood-Finish Recognition Trophy',
      'Ornate Shield Wood-Finish Recognition Trophy',
      'Jubilee Shield Wood-Finish Memento',
      'Star Frame Wood-Finish Appreciation Trophy',
      'Angular Blue Wood-Finish Recognition Trophy',
      'Ribbon Crest Wood-Finish Memento',
      'Triple-Arc Wood-Finish Appreciation Trophy',
      'Basketball Flame Wood-Finish Trophy',
      'Basketball Star Wood-Finish Trophy',
      'Basketball Laurel Wood-Finish Trophy',
      'Gold Leaf Wood-Finish Appreciation Trophy',
      'Ornate Gold Frame Wood-Finish Plaque',
      'Classic Gold Frame Wood-Finish Plaque',
      'Round Gold Plate Wood-Finish Memento',
      'Oval White Sports Recognition Memento',
      'Laurel Oval White Recognition Memento',
      'Rounded Rectangle White Recognition Memento',
      'Black and Gold Volleyball Recognition Memento',
      'Octagonal Black and Gold Recognition Memento',
      'Lattice Sail Black Recognition Memento',
      'Ornate Arch White Recognition Memento',
      'Gold Frame Rosewood Presentation Award',
      'Gold Frame Black Presentation Award',
      'Oval Gold Medallion White Memento',
      'Floral Crest White Recognition Memento',
      'Crown Frame White Recognition Memento',
      'Royal Frame White Recognition Memento',
      'Ornate Heritage Wood-Finish Memento',
      'Red Crest Wood-Finish Recognition Memento',
      'Round Jubilee Wood-Finish Memento',
      'Gold Curve Rosewood Recognition Memento',
      'Red Wave Rosewood Recognition Memento',
      'Classic Crest Rosewood Recognition Memento',
      'Royal Shield Rosewood Recognition Memento',
      'Round Plate Rosewood Recognition Memento',
      'Gold Frame Rosewood Honour Plaque',
      'Gold Frame Rosewood Appreciation Plaque',
      'Rosette Column Rosewood Sports Trophy',
      'Red Leaf Rosewood Recognition Trophy',
      'Framed Gold Rosewood Recognition Plaque',
      'Arched Gold Rosewood Recognition Trophy',
      'Ornate Round Rosewood Recognition Trophy',
      'Floral Round Rosewood Sports Trophy',
      'Crown Shield Rosewood Sports Trophy',
      'Laurel Round Rosewood Recognition Trophy',
      'Gold Frame Rosewood Service Plaque',
      'Gold Frame Rosewood Honour Plaque',
      'Winged Round Rosewood Recognition Memento',
      'Green Star Rosewood Sports Memento',
      'Crown Crest Rosewood Recognition Memento',
      'Open Book Rosewood Recognition Memento',
      'Laurel Book Rosewood Academic Memento',
      'Cricket Star Rosewood Sports Memento',
      'Arched Gold Rosewood Sports Memento',
      'Angular Star Rosewood Achievement Memento',
      'Winged Gold Rosewood Corporate Memento',
      'Curved Gold Rosewood Corporate Memento',
      'White Floral Corporate Recognition Memento',
      'White Line-Art Appreciation Memento',
      'Angled White Lattice Recognition Memento',
      'Leaf Lattice White Recognition Memento',
      'Geometric Lattice White Recognition Memento',
      'Leadership Frame White Recognition Memento',
      'Red Gold-Frame Rosewood Presentation Plaque',
      'Gold Border Rosewood Presentation Plaque',
      'Gold Frame Rosewood Honour Presentation Plaque',
      'Gold Cushion Rosewood Recognition Memento',
      'Gold Frame Rosewood Sports Presentation Plaque',
      'Curved Gold Rosewood Appreciation Memento',
      'Royal Gold-Frame Rosewood Honour Plaque',
      'Gold Shield Rosewood Achievement Memento',
      'Gold Oval Rosewood Recognition Memento',
      'Floral Crest Rosewood Honour Memento',
      'Shield Frame Rosewood Recognition Memento',
      'Round Gold Rosewood Sports Memento',
      'Star Crest Rosewood Achievement Memento',
      'Patterned Shield Rosewood Appreciation Memento',
      'Square Star Rosewood Recognition Plaque',
      'Floral Blue and Gold Rosewood Recognition Plaque',
      'Gold Arch White Sports Recognition Memento',
      'Black Gold-Frame White Recognition Memento',
      'Royal Crest White Recognition Memento',
      'Ashoka Emblem White Recognition Memento',
      'Green Marble-Style White Recognition Memento',
      'Black Gold-Border White Leadership Memento',
      'Blue Marble-Style White Recognition Memento',
      'Black Marble-Style White Corporate Memento',
      'Red Shield Wood-Finish Sports Memento',
      'Red Oval Shield Wood-Finish Sports Memento',
      'Square Gold Frame White Sports Memento',
      'Rounded Gold Frame Black Recognition Memento',
      'Blue Gold-Frame Corporate Recognition Memento',
      'Black Shield Gold-Panel Recognition Memento',
      'White Gold-Frame Sports Recognition Memento',
      'White Gold-Frame Appreciation Memento',
      'Blue Mosaic Gold-Frame Recognition Memento',
      'Green Wood-Panel Desk Recognition Memento',
      'Black Rainbow-Edge Recognition Memento',
      'Black Angular Rainbow Corporate Memento',
      'Black Gold-Panel Appreciation Memento',
      'Black Scroll-Panel Recognition Memento',
      'Black Winged Sports Recognition Memento',
      'Black Ornate Frame Corporate Memento',
      'Round Lattice White Recognition Memento',
      'Round Gold-Frame Black Corporate Memento',
      'Blue Flame White Performance Memento',
      'Blue Wing White Performance Memento',
      'Blue Shield White Excellence Memento',
      'Crown Figure and Plaque Rosewood Award',
      'Star Figure and Plaque Rosewood Award',
      'Gold Frame Purple Appreciation Memento',
      'Tall Purple Gold-Emblem Recognition Memento',
      'Round Gold Plate Rosewood Sports Award',
      'Floral Gold Plate Rosewood Sports Award',
      'Red Floral Plate Rosewood Sports Award',
      'Royal Gold Frame Rosewood Honour Award',
      'Twin-Ring Gold Plate Rosewood Honour Award',
      'Gold Frame White Recognition Award',
      'White Cushion Gold-Frame Recognition Award',
      'Black Emblem Gold-Panel Recognition Award',
      'Blue Ashoka Emblem Recognition Award',
      'Blue Round Emblem Recognition Award',
      'White Gold-Frame Corporate Recognition Award',
      'White Tricolor Corporate Recognition Award',
      'Blue Ashoka Pillar Corporate Award',
      'Blue Cricket Shield Sports Recognition Award',
      'Blue Oval Cultural Recognition Award',
      'Blue Gold-Frame Sports Recognition Award',
      'Blue Heritage Plate Recognition Award',
      'Green Basketball Shield Sports Award',
      'Green Football Shield Sports Award',
      'Green Kabaddi Shield Sports Award',
      'Green Volleyball Shield Sports Award',
      'Green Cricket Shield Sports Award',
      'Red Lattice Sports Recognition Plaque',
      'Red Lattice Appreciation Plaque',
      'Round Gold Frame White Recognition Award',
      'Square Gold Frame White Honour Award',
      'Square Marble Gold Frame Recognition Award',
      'Raised Gold Frame White Recognition Award',
      'Ornate Marble Gold Frame Recognition Award',
      'Classic Marble Gold Frame Recognition Award',
      'Royal Marble Gold Frame Recognition Award',
    ],
  },
];

const curatedNames = new Map<string, string>();
for (const group of curatedGroups) {
  const skus = group.skus.split('|');
  if (skus.length !== group.labels.length) {
    throw new Error(
      `SEO catalogue mismatch: ${skus[0]} has ${skus.length} SKUs and ${group.labels.length} labels`,
    );
  }
  skus.forEach((sku, index) => {
    const label = group.labels[index];
    if (!label) throw new Error(`SEO catalogue label missing for ${sku}`);
    const materialSafeLabel = label
      .replace(/\bRosewood\b/g, 'Wood-Finish')
      .replace(/\bCrystal-Top\b/g, 'Crystal-Style Top');
    const uniqueLabel =
      sku === 'W-2521' ? 'Classic Gold Frame Wood-Finish Honour Plaque' : materialSafeLabel;
    curatedNames.set(sku, uniqueLabel);
  });
}

function titleCase(value: string): string {
  const smallWords = new Set(['and', 'for', 'with']);
  return value
    .toLowerCase()
    .split(' ')
    .filter(Boolean)
    .map((word, index) =>
      index > 0 && smallWords.has(word) ? word : `${word.charAt(0).toUpperCase()}${word.slice(1)}`,
    )
    .join(' ');
}

function accessoryName(sku: string): string {
  const explicitNames: Record<string, string> = {
    '5MM JHARI BASE 02': 'Speckled White Rectangular Trophy Base',
    '8 MM JHARI BASE 01': 'Black Stepped Rectangular Trophy Base',
    '12 MM JHARI BASE 03': 'Black Slot Rectangular Trophy Base',
    '12 MM RED PLAQUE': '12 mm Red Custom Recognition Plaque',
    '7 STAR MEDAL': 'Seven-Star Achievement Medal',
    'ABS BADGE 03 ALSO IN SILVER': 'Brushed Gold and Silver Rectangular Name Badge',
    'BADMINTON 01': 'Gold Badminton Player Trophy Figure',
    'BADMINTON 02': 'Gold Star and Racket Badminton Trophy Topper',
    'BADMINTON 03': 'Gold Rackets and Shuttlecock Trophy Topper',
    'BASKETBALL 01': 'Gold Jump-Shot Basketball Trophy Figure',
    'BODY BULIDER 02': 'Gold Bodybuilder Victory Trophy Figure',
    'BOOK 01': 'Gold Double-Page Academic Trophy Topper',
    'BOOK 02': 'Gold Open Book and Pen Trophy Topper',
    'BOWLING 01': 'Gold Bowling Player Trophy Figure',
    'BOWLING 02': 'Gold Stars, Pins and Ball Bowling Trophy Topper',
    'BOWLING 03': 'Gold Bowling Action Trophy Figure',
    'BRASS BADGE 02': 'Round Patterned Brass Recognition Badge',
    'BRASS BADGE 04': 'Plain Rectangular Brass Name Badge',
    'BRASS BADGE 05': 'Floral-Border Brass Name Badge',
    'BRASS BADGE 06': 'Gold-Border Rectangular Brass Name Badge',
    'BRASS BADGE 07': 'Octagonal Brass Recognition Badge',
    'CHEST FLOWER 05': 'Blue Rosette Recognition Badge',
    'CHEST FLOWER 06': 'Tricolor Rosette Recognition Badge',
    'CHEST FLOWER 07': 'Red and Silver Rosette Recognition Badge',
    'CHEST FLOWER 08': 'Blue and Silver Rosette Recognition Badge',
    'CORNER FOR BASE': 'Decorative Trophy Base Corner Fitting',
    'CRICKET 01': 'Gold Star-Frame Cricket Batter Trophy Topper',
    'CRICKET 02': 'Gold Cricket Batter Action Trophy Figure',
    'CRICKET 04': 'Gold Shield, Stumps and Bat Cricket Trophy Topper',
    'CRICKET 05': 'Gold Stars, Stumps and Ball Cricket Trophy Topper',
    'CRICKET 07': 'Gold Bat and Stumps Cricket Trophy Topper',
    'CRICKET 08': 'Gold Shield Cricket Batter Trophy Topper',
    'CRICKET 09': 'Gold Wicket Action Cricket Trophy Figure',
    'CRICKET 10': 'Gold Star Shield Cricket Trophy Topper',
    'CRICKET 11': 'Gold Bat, Ball and Stumps Cricket Trophy Topper',
    CRYSTAL: 'Clear Crystal-Style Trophy Topper',
    'CRYSTAL CANDY': 'Faceted Crystal-Style Trophy Topper',
    'DOUBLE BASE 01': 'Black Two-Tier Rectangular Trophy Base',
    'DOUBLE BASE 02': 'Red Two-Tier Rectangular Trophy Base',
    'DOUBLE MAGNET 02 ROUND CORNER': 'Round-Corner Double-Magnet Badge Backing',
    FLOWER: 'Gold Floral Trophy Decoration',
    'FOOTBALL 02': 'Gold Action Football Trophy Topper',
    'FOOTBALL 03': 'Gold Standing Football Player Trophy Figure',
    'FOOTBALL 05': 'Gold Bicycle-Kick Football Trophy Figure',
    'FOOTBALL 06': 'Gold Football and Goal Trophy Topper',
    'FOOTBALL 07': 'Gold League Football Trophy Topper',
    'JAGUAR MEDAL': 'Scalloped Gold Achievement Medal',
    'JAIPURI BASE': 'Decorative Jaipuri-Style Trophy Base',
    'KARATE 03': 'Gold High-Kick Karate Trophy Figure',
    'KARATE 04': 'Gold Fighting-Stance Karate Trophy Figure',
    'KNOB 02': 'Round Flame Trophy Finial',
    'KNOB 03': 'Ribbed Oval Trophy Finial',
    'KNOB 04': 'Stepped Crown Trophy Finial',
    'LAPEL PIN 01': 'Plain Round Metal Lapel Pin',
    'LAPEL PIN 02': 'Ridged Round Metal Lapel Pin',
    'LAPEL PIN 05': 'India Map Metal Lapel Pin',
    'LAPEL PIN 11': 'Rotary Wheel Metal Lapel Pin',
    'LAPEL PIN 12': 'Rotary Wordmark Metal Lapel Pin',
    'LION 01': 'Gold Ashoka Lion Capital Trophy Topper',
    'MEDAL 01': 'Classic Round Laurel Award Medal',
    'MEDAL 02': 'Star-Border Gold Award Medal',
    'MEDAL 03': 'Diagonal-Ribbon Gold Award Medal',
    'MEDAL 04': 'Antique Laurel-Branch Award Medal',
    'MEDAL 05': 'Antique Shield and Laurel Award Medal',
    'MEDAL 07': 'Antique Leaf-Wreath Award Medal',
    'MEDAL 08': 'Antique Laurel-Wreath Award Medal',
    'MEDAL 09': 'Red Rainbow-Rim Award Medal',
    'MEDAL 10': 'Black Star-Ring Award Medal',
    'MEDAL 11': 'Tricolor Swirl Award Medal',
    'MEDAL 12': 'Scalloped Gold Victory Medal',
    'MEDAL 13': 'Patterned Gold Victory Medal',
    'MEDAL 14': 'Antique Octagonal Laurel Award Medal',
    'MEDAL 15': 'Antique Leaf-Swirl Award Medal',
    'MEDAL 16': 'Antique Double-Laurel Award Medal',
    'MEDAL 17': 'Embossed Winner Cup Award Medal',
    'MEDAL 18': 'Gold Starburst Award Medal',
    'MEDAL 1ST,2ND,3RD': 'First, Second and Third Place Award Medal',
    'MEDAL 20': 'Square Gold Award Medal',
    'MEDAL CHINA TYPE': 'Winged Laurel Gold Award Medal',
    'MIRROR MEDAL': 'Reflective Mirror-Finish Award Medal',
    'NEW SQ BASE PLASTIC 02': 'Red Stepped Square Trophy Base',
    NIB: 'Gold Nib Trophy Decoration',
    'OLYMPIC MEDAL': 'Olympic-Style Victory Medal',
    'PLASTIC BADGE 01': 'Gold-Trim Rectangular Plastic Name Badge',
    'PLASTIC BADGE 02': 'Silver Rectangular Plastic Name Badge',
    'PLASTIC KEYRING 01': 'Clear Round Custom Photo Keyring',
    'PLASTIC KEYRING 02': 'Clear Rectangular Custom Photo Keyring',
    'PLASTIC MEDAL 01': 'Ornate Gold-Finish Plastic Award Medal',
    'PLASTIC NUT': 'Plastic Trophy Assembly Nut',
    'POCKET BADGE 01': 'Silver Horizontal Pocket Name Badge',
    'POCKET BADGE 03': 'Three-Stud Rectangular Pocket Name Badge',
    'RING CRYSTAL': 'Crystal-Style Ring Trophy Topper',
    'RING CRYSTAL CANDY': 'Faceted Crystal-Style Ring Trophy Topper',
    RODS: 'Trophy Assembly Support Rods',
    'ROUND BASE': 'Round Trophy Display Base',
    'RUNNING 01': 'Gold Sprint Runner Trophy Figure',
    'SHIELD MEDAL': 'Shield-Shape Achievement Medal',
    'SINGLE BASE 01': 'Black Flared Rectangular Trophy Base',
    'SINGLE BASE 02': 'Black Compact Tapered Trophy Base',
    'SINGLE BASE 03': 'Black Tall Square Trophy Base',
    'SINGLE BASE 04': 'Black Wide Rounded Trophy Base',
    'SMILEY BADGE': 'Smiley Recognition Badge',
    'SQ BASE PLASTIC 01': 'Black Square Plastic Trophy Base',
    'SQ BASE PLASTIC 03': 'Translucent Red Square Plastic Trophy Base',
    'SQ BASE PLASTIC 04': 'Red Round-Top Square Plastic Trophy Base',
    'SQ BASE PLASTIC 05': 'Black and Gold Square Plastic Trophy Base',
    'SQ BASE PLASTIC 06': 'Red Marble-Style Square Plastic Trophy Base',
    'STEEL BADGE 01': 'Red-Rim Round Steel Recognition Badge',
    'STEEL BADGE 02': 'Blue-Rim Round Steel Recognition Badge',
    'STEEL BADGE 05': 'Blue-Border Rectangular Steel Name Badge',
    'STEEL BADGE 07': 'Star-Border Rectangular Steel Name Badge',
    'STEEL BADGE 23': 'Three-Stud Rectangular Steel Name Badge',
    'VOLLYBALL 01': 'Gold Volleyball Action Trophy Figure',
  };
  if (explicitNames[sku]) return explicitNames[sku];

  const corrected = sku
    .replace(/\bBODY BULIDER\b/g, 'BODYBUILDER')
    .replace(/\bVOLLYBALL\b/g, 'VOLLEYBALL')
    .replace(/\bSAFTY\b/g, 'SAFETY')
    .replace(/\bALUMINIUM\b/g, 'ALUMINUM')
    .replace(/\bJHARI\b/g, 'TROPHY')
    .replace(/\s+/g, ' ')
    .trim();
  const sportMatch =
    /^(BADMINTON|BASKETBALL|BOWLING|CRICKET|FOOTBALL|GYMNASTIC|KARATE|RUNNING|VOLLEYBALL)\s*(\d+)?$/.exec(
      corrected,
    );
  if (sportMatch) {
    const sportKey = sportMatch[1];
    if (!sportKey) throw new Error(`Unable to identify sport accessory ${sku}`);
    const sport = sportKey === 'GYMNASTIC' ? 'Gymnastics' : titleCase(sportKey);
    return `Gold ${sport} Trophy Figure`;
  }
  if (/^MEDAL\b/.test(corrected)) {
    const design = corrected.replace(/^MEDAL\s*/, '') || 'Classic';
    return `Custom Award Medal - ${titleCase(design)}`;
  }
  return titleCase(corrected)
    .replace(/\bAbs\b/g, 'ABS')
    .replace(/\bMm\b/g, 'mm')
    .replace(/\bSq\b/g, 'Square');
}

export function curatedProductName(sku: string, categorySlug: string): string {
  if (categorySlug === 'bases-and-accessories') return accessoryName(sku);
  const name = curatedNames.get(sku);
  if (!name) throw new Error(`Missing curated SEO name for ${sku}`);
  return name;
}

export function productSeoDescription(name: string, categoryDescription: string): string {
  return `${name}. ${categoryDescription} Available from Delta Industries, Jalandhar for custom branding and bulk-order enquiries.`;
}

export function productSearchTerms(
  name: string,
  sku: string,
  categoryName: string,
  categoryTerms: readonly string[],
): string[] {
  return Array.from(
    new Set([
      ...categoryTerms,
      name.toLowerCase(),
      sku.toLowerCase(),
      `${categoryName.toLowerCase()} manufacturer india`,
      `${categoryName.toLowerCase()} wholesale`,
      'custom trophy manufacturer jalandhar',
      'bulk awards india',
    ]),
  );
}

export function productModelGroup(sku: string): 'LA' | 'F' | 'RA' | 'ACA' | undefined {
  const prefix = sku.split('-')[0]?.toUpperCase();
  return prefix === 'LA' || prefix === 'F' || prefix === 'RA' || prefix === 'ACA'
    ? prefix
    : undefined;
}
